In [8]:
import glob
list_of_files = glob.glob("/Users/rahulporuri/Downloads/SO-survey-data/*")

In [9]:
import pandas as pd

In [100]:
pd.read_table("/Users/rahulporuri/Downloads/SO-survey-data/2011_Stack_Overflow_Survey_Results.csv",
               sep=",", header=0, engine="python", verbose=True)

Filled 1784 NA values in column Which US State or Territory do you live in?
Filled 84 NA values in column How old are you?
Filled 84 NA values in column How many years of IT/Programming experience do you have?
Filled 84 NA values in column How would you best describe the industry you work in?
Filled 167 NA values in column Which best describes the size of your company?
Filled 167 NA values in column Which of the following best describes your occupation?
Filled 203 NA values in column How likely is it that a recommendation you make will be acted upon?
Filled 1452 NA values in column What is your involvement in purchasing? You can choose more than 1.
Filled 1317 NA values in column Unnamed: 9
Filled 2419 NA values in column Unnamed: 10
Filled 2357 NA values in column Unnamed: 11
Filled 2628 NA values in column Unnamed: 12
Filled 2087 NA values in column Unnamed: 13
Filled 2722 NA values in column Unnamed: 14
Filled 1846 NA values in column What types of purchases are you involved in?
Filled 2105 NA values in column Unnamed: 16
Filled 1024 NA values in column Unnamed: 17
Filled 1844 NA values in column Unnamed: 18
Filled 2347 NA values in column Unnamed: 19
Filled 2529 NA values in column Unnamed: 20
Filled 2281 NA values in column What is your budget for outside expenditures (hardware, software, consulting, etc) for 2011?
Filled 2595 NA values in column Unnamed: 22
Filled 2729 NA values in column Unnamed: 23
Filled 2769 NA values in column Unnamed: 24
Filled 2771 NA values in column Unnamed: 25
Filled 2769 NA values in column Unnamed: 26
Filled 2693 NA values in column Unnamed: 27
Filled 1887 NA values in column Unnamed: 28
Filled 215 NA values in column What type of project are you developing?
Filled 1952 NA values in column Which languages are you proficient in?
Filled 1394 NA values in column Unnamed: 31
Filled 1457 NA values in column Unnamed: 32
Filled 2025 NA values in column Unnamed: 33
Filled 2238 NA values in column Unnamed: 34
Filled 2528 NA values in column Unnamed: 35
Filled 1200 NA values in column Unnamed: 36
Filled 1461 NA values in column Unnamed: 37
Filled 2073 NA values in column Unnamed: 38
Filled 2072 NA values in column Unnamed: 39
Filled 2529 NA values in column Unnamed: 40
Filled 2793 NA values in column Unnamed: 41
Filled 2146 NA values in column Unnamed: 42
Filled 223 NA values in column What operating system do you use the most?
Filled 260 NA values in column Please rate your job/career satisfaction
Filled 448 NA values in column Including bonus, what is your annual compensation in USD?
Filled 1974 NA values in column Which technology products do you own? (You can choose more than one)
Filled 2069 NA values in column Unnamed: 47
Filled 2645 NA values in column Unnamed: 48
Filled 2447 NA values in column Unnamed: 49
Filled 2189 NA values in column Unnamed: 50
Filled 2460 NA values in column Unnamed: 51
Filled 2774 NA values in column Unnamed: 52
Filled 2297 NA values in column Unnamed: 53
Filled 1723 NA values in column Unnamed: 54
Filled 2697 NA values in column Unnamed: 55
Filled 2419 NA values in column Unnamed: 56
Filled 2312 NA values in column Unnamed: 57
Filled 2437 NA values in column Unnamed: 58
Filled 2216 NA values in column Unnamed: 59
Filled 1989 NA values in column Unnamed: 60
Filled 2499 NA values in column Unnamed: 61
Filled 2595 NA values in column Unnamed: 62
Filled 308 NA values in column In the last 12 months, how much money have you spent on personal technology-related purchases?
Filled 281 NA values in column Which of our sites do you frequent most?

,What Country or Region do you live in?,Which US State or Territory do you live in?,How old are you?,How many years of IT/Programming experience do you have?,How would you best describe the industry you work in?,Which best describes the size of your company?,Which of the following best describes your occupation?,How likely is it that a recommendation you make will be acted upon?,What is your involvement in purchasing? You can choose more than 1.,Unnamed: 9,...,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,"In the last 12 months, how much money have you spent on personal technology-related purchases?",Which of our sites do you frequent most?
0,Response,Response,Response,Response,Response,Response,Response,Response,Influencer,Recommender,...,AppleTV,iPad,Other netbook,PS3,Xbox,Wii,Other gaming system,other (please specify),Response,Response
1,Africa,NaN,< 20,<2,Consulting,Start Up (1-25),Web Application Developer,Not in a million years,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<$100,NaN
2,Other Europe,NaN,25-29,41310,Software Products,Mature Small Business (25-100),Server Programmer,It's been known to happen,NaN,NaN,...,NaN,NaN,Other netbook,NaN,NaN,NaN,NaN,NaN,$251-$500,Stack Overflow
3,India,NaN,25-29,41435,Software Products,Mid Sized (100-999),Server Programmer,Unless it's stoopid it gets done,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Germany,NaN,< 20,41310,Foundation / Non-Profit,Student,Student,It's been known to happen,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Wii,Other gaming system,NaN,"$501-$1,000",Stack Overflow
5,Other Asia,NaN,35-39,11,Software Products,Start Up (1-25),"Executive (VP of Eng, CTO, CIO, etc.)",I run this place,Influencer,NaN,...,NaN,NaN,NaN,NaN,Xbox,NaN,NaN,NaN,$251-$500,Stack Overflow
6,Australia,NaN,35-39,11,Consulting,Start Up (1-25),Web Application Developer,Unless it's stoopid it gets done,Influencer,NaN,...,NaN,iPad,NaN,NaN,NaN,NaN,NaN,NaN,">$3,000",Stack Overflow
7,United States of America,Illinois,20-24,41310,Manufacturing,Mature Small Business (25-100),"Executive (VP of Eng, CTO, CIO, etc.)",Unless it's stoopid it gets done,Influencer,Recommender,...,NaN,NaN,Other netbook,NaN,NaN,NaN,NaN,multi touch display,">$3,000",Stack Overflow
8,United States of America,Georgia,20-24,41435,Web Services,"Fortune 1000 (1,000+)",Web Application Developer,It's been known to happen,NaN,NaN,...,NaN,NaN,Other netbook,NaN,Xbox,Wii,Other gaming system,NaN,"$1,001-$2,000",None
9,Germany,NaN,35-39,11,Software Products,Mid Sized (100-999),Desktop Application Developer,Unless it's stoopid it gets done,Influencer,Recommender,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"$501-$1,000",Stack Overflow
10,Germany,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,United Kingdom,NaN,35-39,11,Education,Mid Sized (100-999),IT Staff / System Administrator,I run this place,Influencer,Recommender,...,NaN,NaN,NaN,NaN,Xbox,NaN,NaN,NaN,"$1,001-$2,000",Server Fault
12,United Kingdom,NaN,25-29,11,Web Services,Mature Small Business (25-100),Web Application Developer,Unless it's stoopid it gets done,NaN,NaN,...,NaN,NaN,Other netbook,NaN,NaN,Wii,NaN,NaN,$251-$500,Stack Overflow
13,India,NaN,25-29,41435,Software Products,Mature Small Business (25-100),Database Administrator,Once in a blue moon,NaN,Recommender,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"$2,001-$3,000",Stack Overflow
14,United Kingdom,NaN,30-34,11,Education,Mid Sized (100-999),Server Programmer,Unless it's stoopid it gets done,Influencer,Recommender,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"$501-$1,000",Stack Overflow
15,Other Europe,NaN,20-24,41310,Web Services,Student,Server Programmer,It's been known to happen,Influencer,Recommender,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,">$3,000",Stack Overflow
16,United States of America,California,25-29,11,Foundation / Non-Profit,Mid Sized (100-999),Web Application Developer,Unless it's stoopid it gets done,Influencer,Recommender,...,NaN,iPad,NaN,NaN,NaN,Wii,NaN,NaN,"$2,001-$3,000",Stack Overflow
17,Australia,NaN,25-29,41310,Finance / Banking,Mature Small Business (25-100),Manager of Developers or Team Leader,Unless it's stoopid it gets done,Influencer,Recommender,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,">$3,000",Stack Overflow
18,Australia,NaN,30-34,11,Consulting,Mid Sized (100-999),Web Application Developer,It's been known to happen,NaN,Recommender,...,NaN,NaN,NaN,PS3,NaN,Wii,NaN,NaN,"$501-$1,000",Stack Overflow
19,United States of America,Idaho,20-24,41310,Other,Start Up (1-25),Student,Unless it's stoopid it gets done,Influencer,NaN,...,NaN,iPad,NaN,NaN,Xbox,Wii,NaN,NaN,"$1,001-$2,000",Stack Overflow
20,United States of America,Massachusetts,25-29,41310,Software Products,Mid Sized (100-999),Desktop Application Developer,Unless it's stoopid it gets done,NaN,NaN,...,NaN,NaN,NaN,PS3,NaN,NaN,NaN,NaN,$100-$250,Stack Overflow
21,France,NaN,25-29,41435,Web Services,Start Up (1-25),Manager of Developers or Team Leader,Unless it's stoopid it gets done,NaN,Recommender,...,NaN,NaN,Other netbook,NaN,NaN,NaN,NaN,NaN,$251-$500,Stack Overflow
22,United States of America,Virginia,25-29,41310,Other,"Fortune 1000 (1,000+)",IT Staff / System Administrator,It's been known to happen,Influencer,NaN,...,NaN,NaN,NaN,NaN,Xbox,NaN,NaN,NaN,"$1,001-$2,000",Server Fault
23,Germany,NaN,25-29,11,Software Products,Mature Small Business (25-100),Manager of Developers or Team Leader,I run this place,Influencer,Recommender,...,NaN,NaN,NaN,NaN,Xbox,NaN,NaN,NaN,"$501-$1,000",Stack Overflow
24,United States of America,South Carolina,35-39,41435,Software Products,Mature Small Business (25-100),Desktop Application Developer,Unless it's stoopid it gets done,Influencer,Recommender,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"$1,001-$2,000",Stack Overflow
25,United States of America,Oregon,35-39,11,Software Products,"Fortune 1000 (1,000+)",Web Application Developer,Once in a blue moon,Influencer,NaN,...,NaN,NaN,NaN,PS3,NaN,NaN,NaN,NaN,"$2,001-$3,000",Stack Overflow
26,Australasia,NaN,51-60,11,Consulting,"Other (not working, consultant, etc.)",IT Staff / System Administrator,I run this place,Influencer,Recommender,...,NaN,NaN,Other netbook,NaN,NaN,NaN,NaN,NaN,"$2,001-$3,000",Stack Overflow
27,Canada,NaN,30-34,41435,Other,Mature Small Business (25-100),Web Application Developer,Unless it's stoopid it gets done,Influencer,NaN,...,NaN,NaN,NaN,NaN,NaN,Wii,Other gaming system,NaN,$100-$250,Programmers Stack Exchange
28,France,NaN,20-24,41310,Retail,"Fortune 1000 (1,000+)",Web Application Developer,Unless it's stoopid it gets done,Influencer,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"$501-$1,000",Stack Overflow
29,United States of America,Florida,25-29,11,Web Services,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2784,United States of America,California,25-29,41435,Web Services,"Other (not working, consultant, etc.)",Web Application Developer,Unless it's stoopid it gets done,Influencer,Recommender,...,NaN,NaN,Other netbook,NaN,NaN,NaN,NaN,NaN,"$2,001-$3,000",Stack Overflow
2785,United States of America,New York,30-34,41310,Web Services,Start Up (1-25),Other,I run this place,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,$100-$250,Stack Overflow
2786,Canada,NaN,40-50,11,Web Services,Start Up (1-25),Web Application Developer,Unless it's stoopid it gets done,NaN,Recommender,...,NaN,NaN,NaN,PS3,NaN,NaN,NaN,NaN,"$1,001-$2,000",Stack Overflow
2787,United States of America,Florida,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2788,Germany,NaN,25-29,11,Foundation / Non-Profit,Student,Student,Unless it's stoopid it gets done,NaN,NaN,...,NaN,iPad,NaN,NaN,NaN,NaN,NaN,NaN,<$100,Stack Overflow
2789,United States of America,Tennessee,30-34,41435,Software Products,Start Up (1-25),Web Application Developer,Unless it's stoopid it gets done,Influencer,NaN,...,NaN,NaN,NaN,NaN,NaN,Wii,NaN,NaN,"$1,001-$2,000",Stack Overflow
2790,United States of America,California,35-39,11,Software Products,"Fortune 1000 (1,000+)",Desktop Application Developer,Unless it's stoopid it gets done,Influencer,Recommender,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"$501-$1,000",Stack Overflow
2791,Other Asia,NaN,40-50,11,Other,Mid Sized (100-999),Desktop Application Developer,Unless it's stoopid it gets done,NaN,Recommender,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"$1,001-$2,000",Stack Overflow
2792,Africa,NaN,25-29,11,Web Services,Mature Small Business (25-100),Web Application Developer,It's been known to happen,NaN,Recommender,...,NaN,NaN,Other netbook,NaN,Xbox,NaN,Other gaming system,NaN,$251-$500,Stack Overflow
2793,United Kingdom,NaN,30-34,11,Software Products,Mid Sized (100-999),Web Application Developer,It's been known to happen,Influencer,Recommender,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"$501-$1,000",Stack Overflow
2794,United Kingdom,NaN,30-34,11,Web Services,Mature Small Business (25-100),Manager of Developers or Team Leader,It's been known to happen,NaN,Recommender,...,NaN,NaN,NaN,NaN,Xbox,Wii,NaN,NaN,$251-$500,Stack Overflow
2795,United Kingdom,NaN,40-50,11,Consulting,Start Up (1-25),Web Application Developer,It's been known to happen,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Wii,Other gaming system,NaN,"$501-$1,000",Stack Overflow
2796,Germany,NaN,30-34,41435,Web Services,Start Up (1-25),Web Application Developer,Unless it's stoopid it gets done,Influencer,Recommender,...,NaN,NaN,Other netbook,NaN,NaN,NaN,NaN,NaN,$100-$250,Stack Overflow
2797,Other Europe,NaN,20-24,41310,Software Products,Start Up (1-25),Desktop Application Developer,Unless it's stoopid it gets done,Influencer,Recommender,...,NaN,iPad,NaN,NaN,NaN,NaN,NaN,NaN,"$501-$1,000",Stack Overflow
2798,United States of America,Minnesota,35-39,11,Software Products,Mid Sized (100-999),Desktop Application Developer,Unless it's stoopid it gets done,Influencer,Recommender,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"$1,001-$2,000",Stack Overflow
2799,South America,NaN,20-24,<2,Other,Student,Student,Not in a million years,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<$100,Stack Overflow
2800,South America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2801,Australia,NaN,35-39,11,Manufacturing,Mid Sized (100-999),Manager of Developers or Team Leader,Unless it's stoopid it gets done,Influencer,Recommender,...,NaN,NaN,NaN,NaN,Xbox,NaN,NaN,NaN,"$2,001-$3,000",Stack Overflow
2802,Australia,NaN,20-24,41435,Advertising,Start Up (1-25),Web Application Developer,Unless it's stoopid it gets done,NaN,NaN,...,NaN,NaN,Other netbook,NaN,NaN,NaN,NaN,NaN,$251-$500,Stack Overflow
2803,United States of America,Maine,20-24,<2,Other,Start Up (1-25),Other,Once in a blue moon,NaN,NaN,...,AppleTV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"$1,001-$2,000",Meta Stack Overflow
2804,South America,NaN,25-29,41435,Finance / Banking,Start Up (1-25),Web Application Developer,Unless it's stoopid it gets done,NaN,Recommender,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,$251-$500,Stack Overflow
2805,Other Europe,NaN,20-24,41435,Software Products,Student,Student,I run this place,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2806,United States of America,New York,40-50,11,Consulting,Start Up (1-25),Other,It's been known to happen,Influencer,Recommender,...,NaN,NaN,Other netbook,NaN,NaN,NaN,Other gaming system,NaN,$251-$500,Stack Overflow
2807,Middle East,NaN,30-34,41435,Software Products,Start Up (1-25),Web Application Developer,I run this place,Influencer,Recommender,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2808,Other Europe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2809,United States of America,Utah,40-50,11,Consulting,Start Up (1-25),Web Application Developer,I run this place,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,$100-$250,Stack Overflow
2810,United States of America,Indiana,20-24,41435,Software Products,Mid Sized (100-999),Web Application Developer,It's been known to happen,Influencer,Recommender,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"$501-$1,000",Stack Overflow
2811,Other Asia,NaN,20-24,41310,Other,Mature Small Business (25-100),Web Application Developer,Unless it's stoopid it gets done,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,none of the above,"$501-$1,000",Stack Overflow
2812,United States of America,Iowa,25-29,41435,Web Services,Mature Small Business (25-100),Web Application Developer,It's been known to happen,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Wii,NaN,NaN,"$1,001-$2,000",Stack Overflow
2813,United States of America,Colorado,51-60,41310,Software Products,Mid Sized (100-999),Kernel / Driver Developer,It's been known to happen,Influencer,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,">$3,000",Stack Overflow

In [166]:
for file in list_of_files:
    print(file.split("/")[-1].split("_")[0], pd.read_table(file, sep=",", header=0, engine="python").shape[0])

2011 2814
2012 6244
2013 Stack Overflow Survey Responses.csv 9743
2014 7644
2015 26087
2016 56030
2017 51392

In [165]:
for file in list_of_files:
    print(file.split("/")[-1])
    df = pd.read_table(file, sep=",", header=0, engine="python")
    print(df.shape)
    try:
        col_wt_country_data = df.columns.str.lower().str.contains("country")
        country_data = df[df.columns[col_wt_country_data].get_values()[0]]
        print(country_data.astype("category").value_counts())  
    except:
        pass

2011_Stack_Overflow_Survey_Results.csv
(2814, 65)
United States of America    1037
Other Europe                 451
United Kingdom               314
Canada                       156
Australia                    112
Germany                      106
India                         95
South America                 91
Other Asia                    81
Middle East                   73
France                        60
Netherlands                   55
Africa                        43
Russia                        41
Italy                         35
Australasia                   29
Mexico                        20
North America (Other)          8
Central America                6
Response                       1
Name: What Country or Region do you live in?, dtype: int64
2012_Stack_Overflow_Survey_Results.csv
(6244, 75)
United States of America    1785
Other Europe                1168
United Kingdom               589
India                        537
Canada                       348
Germany                      273
Other Asia                   221
Australia                    185
South America                182
Russia                       162
Netherlands                  136
France                       135
Middle East                  124
Italy                        110
Australasia                  105
Africa                        92
Mexico                        32
North America (Other)         23
Central America               21
Bangladesh                    15
Response                       1
Name: What Country or Region do you live in?, dtype: int64
2013 Stack Overflow Survey Responses.csv
(9743, 128)
United States of America    3181
Other Europe                1626
United Kingdom               935
India                        737
Germany                      583
Canada                       490
Other Asia                   367
Australia                    246
Russia                       241
France                       232
South America                225
Netherlands                  207
Middle East                  198
Italy                        151
Australasia                  118
Africa                       115
Mexico                        29
North America (Other)         26
Central America               17
Bangladesh                    17
Response                       1
Name: What Country or Region do you live in?, dtype: int64
2014_Stack_Overflow_Survey_Responses.csv
(7644, 120)
United States             2128
India                      881
United Kingdom             721
Germany                    455
Canada                     306
France                     198
Australia                  182
Russia                     166
Netherlands                154
Poland                     131
Italy                      125
Israel                     117
Sweden                      99
Spain                       97
Brazil                      96
Switzerland                 83
Ukraine                     69
Turkey                      68
Austria                     66
Romania                     63
Belgium                     62
Denmark                     56
China                       54
Ireland                     53
Greece                      48
Pakistan                    48
Finland                     47
Czech Republic              46
New Zealand                 46
Bulgaria                    42
                          ...
Tunisia                      8
Saudi Arabia                 8
Other                        8
Jordan                       7
Georgia                      7
Nepal                        6
Uruguay                      6
Morocco                      6
Kazakhstan                   6
Bosnia and Herzegovina       6
Venezuela                    5
Iceland                      5
Bolivia                      5
Moldova                      5
Malta                        4
Myanmar [Burma]              4
Ecuador                      4
Puerto Rico                  3
Costa Rica                   3
Palestine                    3
Cyprus                       3
El Salvador                  2
Cambodia                     2
Ghana                        2
Guatemala                    2
Luxembourg                   2
Kuwait                       2
Nigeria                      1
Kenya                        1
Response                     1
Name: What Country do you live in?, dtype: int64
2015_Stack_Overflow_Developer_Survey_Responses.csv
(26087, 222)
2016_Stack_Overflow_Survey_Responses.csv
(56030, 66)
United States          13539
United Kingdom          4573
India                   4193
Germany                 3883
Canada                  2024
Poland                  1971
France                  1626
Russian Federation      1419
Sweden                  1328
Netherlands             1188
Italy                   1137
Australia               1117
Spain                   1026
Brazil                  1015
Romania                  942
Ukraine                  802
Denmark                  606
Switzerland              574
Belgium                  543
Portugal                 496
Austria                  482
South Africa             479
Turkey                   445
Mexico                   444
Finland                  440
Israel                   439
Ireland {Republic}       427
Greece                   393
Iran                     372
Czech Republic           372
                       ...
Antigua & Deps             2
Malawi                     2
Vatican City               2
Zambia                     2
St Kitts & Nevis           1
Somalia                    1
Sierra Leone               1
Tajikistan                 1
Seychelles                 1
Antarctica                 1
Togo                       1
Vanuatu                    1
Sao Tome & Principe        1
Grenada                    1
San Marino                 1
Rwanda                     1
Palau                      1
Oman                       1
Burkina                    1
Burundi                    1
Guinea                     1
Central African Rep        1
Chad                       1
Mozambique                 1
Monaco                     1
Mauritania                 1
Dominica                   1
East Timor                 1
Gabon                      1
Niger                      1
Name: country, dtype: int64
2017_Stack_Overflow_Survey_Responses.csv
(51392, 154)
United States                     11455
India                              5197
United Kingdom                     4395
Germany                            4143
Canada                             2233
France                             1740
Poland                             1290
Australia                           913
Russian Federation                  873
Spain                               864
Netherlands                         855
Italy                               781
Brazil                              777
Sweden                              611
Switzerland                         595
Israel                              575
Romania                             561
Iran                                507
Austria                             477
Pakistan                            454
Czech Republic                      411
Belgium                             404
South Africa                        380
Turkey                              363
Ukraine                             356
Mexico                              351
Ireland                             345
Hungary                             332
Philippines                         328
Slovenia                            303
                                  ...
Burundi                               2
Cayman Islands                        2
British Indian Ocean Territory        1
Seychelles                            1
Montserrat                            1
Christmas Island                      1
Monaco                                1
Djibouti                              1
Mali                                  1
Falkland Islands                      1
Northern Mariana Islands              1
Chad                                  1
Macau                                 1
Lesotho                               1
Cape Verde                            1
Cook Islands                          1
Gibraltar                             1
Bahamas                               1
Pitcairn Island                       1
French Guyana                         1
S. Georgia & S. Sandwich Isls.        1
Vatican City State                    1
Saint Helena                          1
Gabon                                 1
Burkina Faso                          1
Turkmenistan                          1
Heard and McDonald Islands            1
Guinea                                1
Guam                                  1
Comoros                               1
Name: Country, dtype: int64

In [173]:
for file in list_of_files:
    df = pd.read_table(file, sep=",", header=0, engine="python")
    print(file.split("/")[-1], df.shape)
    col_wt_salary_data = df.columns.str.lower().str.contains("salary") | df.columns.str.lower().str.contains("compensation")
    try:
        print(df.columns[col_wt_salary_data].get_values())
        salary_data = df[df.columns[col_wt_salary_data].get_values()[0]]
        try:
            print(salary_data.astype("float").value_counts())
        except:
            print(salary_data.astype("category").value_counts())
    except:
        pass

2011_Stack_Overflow_Survey_Results.csv (2814, 65)
['Including bonus, what is your annual compensation in USD?']
$40,000 - $60,000       415
$60,000 - $80,000       413
$20,000 - $40,000       318
$80,000 - $100,000      292
<$20,000                283
$100,000 - $120,000     222
Student / Unemployed    215
>$140,000               110
$120,000 - $140,000      97
Response                  1
Name: Including bonus, what is your annual compensation in USD?, dtype: int64
2012_Stack_Overflow_Survey_Results.csv (6244, 75)
['Including bonus, what is your annual compensation in USD?']
Rather not say          982
$40,000 - $60,000       691
<$20,000                688
$20,000 - $40,000       647
$60,000 - $80,000       609
Student / Unemployed    515
$80,000 - $100,000      479
$100,000 - $120,000     298
>$140,000               181
$120,000 - $140,000     147
Response                  1
Name: Including bonus, what is your annual compensation in USD?, dtype: int64
2013 Stack Overflow Survey Responses.csv (9743, 128)
['Including bonus, what is your annual compensation in USD?']
Rather not say          1128
$60,000 - $80,000        986
$40,000 - $60,000        911
$20,000 - $40,000        864
<$20,000                 767
$80,000 - $100,000       727
Student / Unemployed     570
$100,000 - $120,000      528
>$140,000                323
$120,000 - $140,000      254
Response                   1
Name: Including bonus, what is your annual compensation in USD?, dtype: int64
2014_Stack_Overflow_Survey_Responses.csv (7644, 120)
['Including bonus, what is your annual compensation in USD?']
Student / Unemployed    1147
Rather not say          1130
<$20,000                 970
$40,000 - $60,000        794
$20,000 - $40,000        746
$60,000 - $80,000        697
$80,000 - $100,000       587
$100,000 - $120,000      386
>$140,000                244
$120,000 - $140,000      199
Response                   1
Name: Including bonus, what is your annual compensation in USD?, dtype: int64
2015_Stack_Overflow_Developer_Survey_Responses.csv (26087, 222)
[]
2016_Stack_Overflow_Survey_Responses.csv (56030, 66)
['salary_range' 'salary_midpoint']
Less than $10,000         7686
$10,000 - $20,000         4977
$20,000 - $30,000         3677
$30,000 - $40,000         3429
$40,000 - $50,000         3291
$50,000 - $60,000         3138
$60,000 - $70,000         2823
$70,000 - $80,000         2500
Rather not say            2246
Unemployed                1880
$80,000 - $90,000         1834
$90,000 - $100,000        1684
$100,000 - $110,000       1653
$110,000 - $120,000       1086
$120,000 - $130,000        917
More than $200,000         661
$130,000 - $140,000        608
$140,000 - $150,000        569
$150,000 - $160,000        472
$160,000 - $170,000        278
Other (please specify)     253
$170,000 - $180,000        206
$180,000 - $190,000        136
$190,000 - $200,000        117
Name: salary_range, dtype: int64
2017_Stack_Overflow_Survey_Responses.csv (51392, 154)
['AssessJobCompensation' 'Salary' 'ExpectedSalary']
Important               9788
Very important          7757
Somewhat important      3667
Not very important       778
Not at all important     156
Name: AssessJobCompensation, dtype: int64

In [174]:
for file in list_of_files:
    df = pd.read_table(file, sep=",", header=0, engine="python")
    print(file.split("/")[-1], df.shape)
    col_wt_remote_data = df.columns.str.lower().str.contains("remote") | df.columns.str.lower().str.contains("home")
    try:
        print(df.columns[col_wt_remote_data].get_values())
        remote_data = df[df.columns[col_wt_remote_data].get_values()[0]]
        print(remote_data.astype("category").value_counts())
    except:
        pass

2011_Stack_Overflow_Survey_Results.csv (2814, 65)
[]
2012_Stack_Overflow_Survey_Results.csv (6244, 75)
[]
2013 Stack Overflow Survey Responses.csv (9743, 128)
[]
2014_Stack_Overflow_Survey_Responses.csv (7644, 120)
['Do you work remotely?' 'Do you enjoy working remotely?'
 'Where do you work remotely most of the time?']
Occasionally        3132
Never               2606
Full-time Remote     762
Part-time Remote     719
Response               1
Name: Do you work remotely?, dtype: int64
2015_Stack_Overflow_Developer_Survey_Responses.csv (26087, 222)
[]
2016_Stack_Overflow_Survey_Responses.csv (56030, 66)
['remote']
I rarely work remotely    19212
Never                      8946
Part-time remote           7088
Full-time remote           4872
Name: remote, dtype: int64
2017_Stack_Overflow_Survey_Responses.csv (51392, 154)
['HomeRemote' 'AssessJobRemote' 'CollaborateRemote']
A few days each month                                      15454
Never                                                      13975
All or almost all the time (I'm full-time remote)           4905
Less than half the time, but at least one day each week     4147
More than half, but not all, the time                       1909
It's complicated                                            1849
About half the time                                         1769
Name: HomeRemote, dtype: int64

In [176]:
for file in list_of_files:
    df = pd.read_table(file, sep=",", header=0, engine="python")
    print(file.split("/")[-1], df.shape)
    col_wt_salary_data = df.columns.str.lower().str.contains("last") | df.columns.str.lower().str.contains("new")
    try:
        print(df.columns[col_wt_salary_data].get_values())
        salary_data = df[df.columns[col_wt_salary_data].get_values()[0]]
        print(salary_data.astype("category").value_counts())
    except:
        pass

2011_Stack_Overflow_Survey_Results.csv (2814, 65)
[ 'In the last 12 months, how much money have you spent on personal technology-related purchases? ']
$1,001-$2,000    569
$501-$1,000      505
$251-$500        367
>$3,000          280
$100-$250        280
$2,001-$3,000    265
<$100            239
Response           1
Name: In the last 12 months, how much money have you spent on personal technology-related purchases? , dtype: int64
2012_Stack_Overflow_Survey_Results.csv (6244, 75)
[ 'In the last 12 months, how much money have you spent on personal technology-related purchases? ']
$1,001-$2,000    1089
$501-$1,000      1019
$251-$500         818
$100-$250         763
<$100             671
>$3,000           471
$2,001-$3,000     466
Response            1
Name: In the last 12 months, how much money have you spent on personal technology-related purchases? , dtype: int64
2013 Stack Overflow Survey Responses.csv (9743, 128)
['Have you changed jobs in the last 12 months?'
 'In the last 12 months, how much money have you spent on personal technology-related purchases?']
No          4970
Yes         2422
Response       1
Name: Have you changed jobs in the last 12 months?, dtype: int64
2014_Stack_Overflow_Survey_Responses.csv (7644, 120)
['Have you changed jobs in the last 12 months?'
 'Are you currently looking for a job or open to new opportunities?'
 'How often do you find solutions to your programming problems on Stack Overflow without asking a new question?']
No          4533
Yes         1923
Response       1
Name: Have you changed jobs in the last 12 months?, dtype: int64
2015_Stack_Overflow_Developer_Survey_Responses.csv (26087, 222)
[]
2016_Stack_Overflow_Survey_Responses.csv (56030, 66)
['why_learn_new_tech' 'open_to_new_job' 'new_job_value' 'important_newtech'
 'important_buildnew']
I want to be a better developer                   16236
I'm curious                                       13231
To keep my skills up to date                       7400
To build a specific product I have in mind         3647
I learn new technology when my job requires it     2766
To pursue career goals                             2095
Other (please specify)                              770
Name: why_learn_new_tech, dtype: int64
2017_Stack_Overflow_Survey_Responses.csv (51392, 154)
['LearningNewTech' 'LastNewJob' 'StackOverflowNewQuestion']
Strongly agree       15318
Agree                12452
Somewhat agree        3042
Disagree               370
Strongly disagree      122
Name: LearningNewTech, dtype: int64

In [178]:
for file in list_of_files:
    df = pd.read_table(file, sep=",", header=0, engine="python")
    print(file.split("/")[-1], df.shape)
    col_wt_salary_data = df.columns.str.lower().str.contains("gender") | df.columns.str.lower().str.contains("sex")
    try:
        print(df.columns[col_wt_salary_data].get_values())
        salary_data = df[df.columns[col_wt_salary_data].get_values()[0]]
        print(salary_data.astype("category").value_counts())
    except:
        pass

2011_Stack_Overflow_Survey_Results.csv (2814, 65)
[]
2012_Stack_Overflow_Survey_Results.csv (6244, 75)
[]
2013 Stack Overflow Survey Responses.csv (9743, 128)
[]
2014_Stack_Overflow_Survey_Responses.csv (7644, 120)
['What is your gender?']
Male                      6864
Female                     352
Prefer not to disclose     130
Response                     1
Name: What is your gender?, dtype: int64
2015_Stack_Overflow_Developer_Survey_Responses.csv (26087, 222)
[]
2016_Stack_Overflow_Survey_Responses.csv (56030, 66)
['gender']
Male                      51388
Female                     3202
Prefer not to disclose      722
Other                       274
Name: gender, dtype: int64
2017_Stack_Overflow_Survey_Responses.csv (51392, 154)
['Gender']
Male                                                       31589
Female                                                      2600
Other                                                        225
Male; Other                                                  171
Gender non-conforming                                        160
Male; Gender non-conforming                                   65
Female; Transgender                                           56
Transgender                                                   55
Female; Gender non-conforming                                 29
Male; Female; Transgender; Gender non-conforming; Other       15
Transgender; Gender non-conforming                            15
Male; Female                                                  15
Male; Transgender                                             11
Female; Transgender; Gender non-conforming                     8
Male; Female; Transgender; Gender non-conforming               7
Gender non-conforming; Other                                   4
Male; Transgender; Gender non-conforming                       4
Male; Female; Transgender                                      4
Male; Gender non-conforming; Other                             3
Male; Female; Other                                            2
Male; Female; Gender non-conforming                            1
Female; Transgender; Other                                     1
Female; Transgender; Gender non-conforming; Other              1
Male; Female; Gender non-conforming; Other                     1
Male; Female; Transgender; Other                               1
Female; Other                                                  1
Female; Gender non-conforming; Other                           1
Male; Transgender; Other                                       1
Transgender; Other                                             1
Name: Gender, dtype: int64

In [180]:
df = pd.read_table("/Users/rahulporuri/Downloads/SO-survey-data/2011_Stack_Overflow_Survey_Results.csv",
                   engine="python", sep=",")

In [196]:
df.iloc[:, 46:63]

,Which technology products do you own? (You can choose more than one),Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62
0,iPhone,Android,Blackberry,Other Smart Phone,Regular Mobile Phone,Kindle,Nook,Blu-Ray,HDTV,AppleTV,iPad,Other netbook,PS3,Xbox,Wii,Other gaming system,other (please specify)
1,iPhone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,iPhone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other netbook,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,Regular Mobile Phone,Kindle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wii,Other gaming system,NaN
5,NaN,Android,NaN,NaN,Regular Mobile Phone,Kindle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Xbox,NaN,NaN,NaN
6,iPhone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,iPad,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other netbook,NaN,NaN,NaN,NaN,multi touch display
8,NaN,Android,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other netbook,NaN,Xbox,Wii,Other gaming system,NaN
9,iPhone,NaN,NaN,NaN,NaN,NaN,NaN,Blu-Ray,HDTV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,iPhone,NaN,NaN,NaN,NaN,Kindle,NaN,NaN,HDTV,NaN,NaN,NaN,NaN,Xbox,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,Regular Mobile Phone,NaN,NaN,Blu-Ray,HDTV,NaN,NaN,Other netbook,NaN,NaN,Wii,NaN,NaN
13,NaN,NaN,NaN,NaN,Regular Mobile Phone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,iPhone,NaN,NaN,NaN,NaN,Kindle,NaN,NaN,HDTV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,iPhone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HDTV,NaN,iPad,NaN,NaN,NaN,Wii,NaN,NaN
17,NaN,NaN,Blackberry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,iPhone,NaN,NaN,NaN,NaN,NaN,NaN,Blu-Ray,HDTV,NaN,NaN,NaN,PS3,NaN,Wii,NaN,NaN
19,NaN,Android,NaN,NaN,NaN,NaN,NaN,NaN,HDTV,NaN,iPad,NaN,NaN,Xbox,Wii,NaN,NaN
20,iPhone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HDTV,NaN,NaN,NaN,PS3,NaN,NaN,NaN,NaN
21,NaN,Android,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other netbook,NaN,NaN,NaN,NaN,NaN
22,iPhone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Xbox,NaN,NaN,NaN
23,NaN,NaN,NaN,Other Smart Phone,NaN,NaN,NaN,Blu-Ray,NaN,NaN,NaN,NaN,NaN,Xbox,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,Regular Mobile Phone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,Android,NaN,NaN,NaN,NaN,NaN,Blu-Ray,NaN,NaN,NaN,NaN,PS3,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,Other Smart Phone,NaN,Kindle,NaN,NaN,NaN,NaN,NaN,Other netbook,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wii,Other gaming system,NaN
28,iPhone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2784,NaN,Android,NaN,NaN,NaN,NaN,NaN,NaN,HDTV,NaN,NaN,Other netbook,NaN,NaN,NaN,NaN,NaN
2785,NaN,NaN,Blackberry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2786,NaN,NaN,NaN,NaN,Regular Mobile Phone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PS3,NaN,NaN,NaN,NaN
2787,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2788,NaN,NaN,NaN,NaN,Regular Mobile Phone,NaN,NaN,NaN,NaN,NaN,iPad,NaN,NaN,NaN,NaN,NaN,NaN
2789,iPhone,NaN,NaN,NaN,NaN,Kindle,NaN,NaN,HDTV,NaN,NaN,NaN,NaN,NaN,Wii,NaN,NaN
2790,NaN,Android,NaN,NaN,NaN,Kindle,NaN,Blu-Ray,HDTV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2791,NaN,NaN,NaN,NaN,Regular Mobile Phone,Kindle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2792,NaN,NaN,NaN,Other Smart Phone,NaN,NaN,NaN,Blu-Ray,HDTV,NaN,NaN,Other netbook,NaN,Xbox,NaN,Other gaming system,NaN
2793,iPhone,NaN,NaN,NaN,NaN,NaN,NaN,Blu-Ray,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2794,NaN,NaN,NaN,NaN,Regular Mobile Phone,NaN,NaN,NaN,HDTV,NaN,NaN,NaN,NaN,Xbox,Wii,NaN,NaN
2795,iPhone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wii,Other gaming system,NaN
2796,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other netbook,NaN,NaN,NaN,NaN,NaN
2797,iPhone,Android,Blackberry,Other Smart Phone,NaN,NaN,NaN,NaN,NaN,NaN,iPad,NaN,NaN,NaN,NaN,NaN,NaN
2798,NaN,Android,NaN,Other Smart Phone,NaN,Kindle,NaN,Blu-Ray,HDTV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2799,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2801,NaN,NaN,NaN,NaN,Regular Mobile Phone,Kindle,NaN,Blu-Ray,HDTV,NaN,NaN,NaN,NaN,Xbox,NaN,NaN,NaN
2802,iPhone,Android,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other netbook,NaN,NaN,NaN,NaN,NaN
2803,iPhone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AppleTV,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2804,NaN,NaN,NaN,Other Smart Phone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2805,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2806,NaN,NaN,NaN,NaN,Regular Mobile Phone,NaN,NaN,NaN,NaN,NaN,NaN,Other netbook,NaN,NaN,NaN,Other gaming system,NaN
2807,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2808,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2809,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Blu-Ray,HDTV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2810,NaN,Android,NaN,NaN,NaN,NaN,NaN,Blu-Ray,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2811,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,none of the above
2812,iPhone,NaN,NaN,NaN,NaN,NaN,NaN,Blu-Ray,HDTV,NaN,NaN,NaN,NaN,NaN,Wii,NaN,NaN
2813,NaN,NaN,NaN,Other Smart Phone,NaN,Kindle,NaN,Blu-Ray,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [190]:
print(df.columns)

Index(['What Country or Region do you live in?',
       'Which US State or Territory do you live in?', 'How old are you?',
       'How many years of IT/Programming experience do you have?',
       'How would you best describe the industry you work in?',
       'Which best describes the size of your company?',
       'Which of the following best describes your occupation?',
       'How likely is it that a recommendation you make will be acted upon?',
       'What is your involvement in purchasing? You can choose more than 1.',
       'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14',
       'What types of purchases are you involved in?', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20',
       'What is your budget for outside expenditures (hardware, software, consulting, etc) for 2011?',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28',
       'What type of project are you developing?',
       'Which languages are you proficient in?', 'Unnamed: 31', 'Unnamed: 32',
       'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36',
       'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40',
       'Unnamed: 41', 'Unnamed: 42',
       'What operating system do you use the most?',
       'Please rate your job/career satisfaction',
       'Including bonus, what is your annual compensation in USD?',
       'Which technology products do you own? (You can choose more than one)',
       'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50',
       'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54',
       'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58',
       'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62',
       'In the last 12 months, how much money have you spent on personal technology-related purchases? ',
       'Which of our sites do you frequent most?'],
      dtype='object')

In [197]:
df = pd.read_table("/Users/rahulporuri/Downloads/SO-survey-data/2012_Stack_Overflow_Survey_Results.csv",
                   engine="python", sep=",")

In [218]:
df.iloc[:5, 64:]

,"In the last 12 months, how much money have you spent on personal technology-related purchases?",Please rate the advertising you've seen on Stack Overflow,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,What advertisers do you remember seeing on Stack Overflow?,What is your current Stack Overflow reputation?,Which of our sites do you frequent most?,Unnamed: 74
0,Response,The ads are relevant,The ads are entertaining,The ads are Informative,I click on ads that interest me,I've taken a trial/purchased a product from ads,What ads? I use an ad blocker,Open-Ended Response,Response,Response,Other Stack Exchange (please specify)
1,"$501-$1,000",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,$100-$250,Neutral,Agree,Agree,Strongly Disagree,Strongly Disagree,Disagree,NaN,Don't have an account,Stack Overflow,NaN
3,"$1,001-$2,000",Neutral,Neutral,Neutral,Neutral,Neutral,Strongly Agree,NaN,1,Stack Overflow,NaN
4,"$1,001-$2,000",Agree,Strongly Disagree,Disagree,Disagree,Strongly Disagree,Disagree,None !,Don't have an account,Stack Overflow,NaN

In [202]:
for file in list_of_files:
    print(file.split("/")[-1].split("_")[0], pd.read_table(file, sep=",", header=0, engine="python").shape)

2011 (2814, 65)
2012 (6244, 75)
2013 Stack Overflow Survey Responses.csv (9743, 128)
2014 (7644, 120)
2015 (26087, 222)
2016 (56030, 66)
2017 (51392, 154)

In [219]:
for file in list_of_files:
    print(file.split("/")[-1].split("_")[0], pd.read_table(file, sep=",", header=0, engine="python").shape)

2011 (2814, 65)
2012 (6244, 75)
2013 Stack Overflow Survey Responses.csv (9743, 128)
2014 (7644, 120)
2015 (26087, 222)
2016 (56030, 66)
2017 (51392, 154)